name: Deploy Firebase Workflow

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nuxt/actions-yarn@master
      with:
        args: install
    - uses: nuxt/actions-yarn@master
      with:
        args: build
    - name: deploy
      run: yarn firebase deploy --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
